/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as DonanteNombreRouteImport } from './routes/donante/$nombre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DonanteNombreRoute = DonanteNombreRouteImport.update({
  id: '/donante/$nombre',
  path: '/donante/$nombre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/donante/$nombre': typeof DonanteNombreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/donante/$nombre': typeof DonanteNombreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/export': typeof ApiExportRoute
  '/donante/$nombre': typeof DonanteNombreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/export' | '/donante/$nombre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/export' | '/donante/$nombre'
  id: '__root__' | '/' | '/api/export' | '/donante/$nombre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExportRoute: typeof ApiExportRoute
  DonanteNombreRoute: typeof DonanteNombreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donante/$nombre': {
      id: '/donante/$nombre'
      path: '/donante/$nombre'
      fullPath: '/donante/$nombre'
      preLoaderRoute: typeof DonanteNombreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExportRoute: ApiExportRoute,
  DonanteNombreRoute: DonanteNombreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
